/* 64c96d906268f26574e6968a864466089d226f5b
 * This file is automatically generated by graphql-let. */

import * as Apollo from '@apollo/client';
export declare type Maybe<T> = T | null;
export declare type Exact<T extends {
    [key: string]: unknown;
}> = {
    [K in keyof T]: T[K];
};
export declare type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
    [SubKey in K]?: Maybe<T[SubKey]>;
};
export declare type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
    [SubKey in K]: Maybe<T[SubKey]>;
};
/** All built-in and custom scalars, mapped to their actual values */
export declare type Scalars = {
    ID: string;
    String: string;
    Boolean: boolean;
    Int: number;
    Float: number;
};
export declare type EditStreamInput = {
    description?: Maybe<Scalars['String']>;
    title?: Maybe<Scalars['String']>;
    url?: Maybe<Scalars['String']>;
};
export declare type Mutation = {
    __typename?: 'Mutation';
    addStream: Stream;
    deleteStream: Scalars['Boolean'];
    editStream: Stream;
    login?: Maybe<User>;
    logout: Scalars['Boolean'];
    register: User;
};
export declare type MutationAddStreamArgs = {
    data: StreamInput;
};
export declare type MutationDeleteStreamArgs = {
    streamId: Scalars['Float'];
};
export declare type MutationEditStreamArgs = {
    data: EditStreamInput;
    streamId: Scalars['Float'];
};
export declare type MutationLoginArgs = {
    email: Scalars['String'];
    password: Scalars['String'];
};
export declare type MutationRegisterArgs = {
    data: RegisterInput;
};
export declare type Query = {
    __typename?: 'Query';
    hello: Scalars['String'];
    me?: Maybe<User>;
    stream?: Maybe<Stream>;
    streams: Array<Stream>;
};
export declare type QueryStreamArgs = {
    streamId: Scalars['Float'];
};
export declare type RegisterInput = {
    email: Scalars['String'];
    password: Scalars['String'];
};
/** Stream */
export declare type Stream = {
    __typename?: 'Stream';
    description?: Maybe<Scalars['String']>;
    id: Scalars['ID'];
    title: Scalars['String'];
    url: Scalars['String'];
    user: User;
};
export declare type StreamInput = {
    description?: Maybe<Scalars['String']>;
    title: Scalars['String'];
    url: Scalars['String'];
};
/** User */
export declare type User = {
    __typename?: 'User';
    email: Scalars['String'];
    id: Scalars['ID'];
    streams?: Maybe<Array<Stream>>;
};
export declare type StreamQueryVariables = Exact<{
    streamId: Scalars['Float'];
}>;
export declare type StreamQuery = ({
    __typename?: 'Query';
} & {
    stream?: Maybe<({
        __typename?: 'Stream';
    } & Pick<Stream, 'id' | 'title' | 'description' | 'url'> & {
        user: ({
            __typename?: 'User';
        } & Pick<User, 'id' | 'email'>);
    })>;
});
export declare const StreamDocument: Apollo.DocumentNode;
/**
 * __useStreamQuery__
 *
 * To run a query within a React component, call `useStreamQuery` and pass it any options that fit your needs.
 * When your component renders, `useStreamQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useStreamQuery({
 *   variables: {
 *      streamId: // value for 'streamId'
 *   },
 * });
 */
export declare function useStreamQuery(baseOptions: Apollo.QueryHookOptions<StreamQuery, StreamQueryVariables>): Apollo.QueryResult<StreamQuery, Exact<{
    streamId: number;
}>>;
export declare function useStreamLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<StreamQuery, StreamQueryVariables>): Apollo.QueryTuple<StreamQuery, Exact<{
    streamId: number;
}>>;
export declare type StreamQueryHookResult = ReturnType<typeof useStreamQuery>;
export declare type StreamLazyQueryHookResult = ReturnType<typeof useStreamLazyQuery>;
export declare type StreamQueryResult = Apollo.QueryResult<StreamQuery, StreamQueryVariables>;
